const tables = [
  "users",
  "auth_sessions",
  "provider_connections",
  "imported_events",
  "card_opportunities",
  "relationship_memories",
  "card_projects",
  "render_packets",
  "orders",
  "order_events",
  "vendor_quotes",
  "consent_records",
  "data_requests",
  "audit_log"
];

const report = {
  service: "customcard-demo-reset",
  status: "ready",
  mode: "contract-preview",
  route: "/api/admin/demo-reset",
  tables,
  rows: 17,
  signedArtifactUrls: true,
  idempotencyRequired: true,
  adminSessionRequired: true,
  rawContentStored: false,
  liveExternalCalls: false,
  realOrdersEnabled: false,
  blockers: []
};

if (process.argv.includes("--sql")) {
  console.log("-- CustomCard demo reset preview; execute only against an isolated reviewer database.");
  console.log("-- Exact DELETE and INSERT statements are generated by buildDemoSeedSqlPreview in src/demoSeed.ts.");
  console.log("-- This script is a no-live-DB doctor surface; it does not mutate persistence.");
} else {
  console.log(JSON.stringify(report, null, 2));
}
